note

	description: "This file has been generated by EWG. Do not edit. Changes will be lost!"

	generator: "Eiffel Wrapper Generator"

class PLTRANSFORM_DISPATCHER


inherit
	PLTRANSFORM_CALLBACK_DISPATCHER

create
	make

feature

	make
		do

		end

feature -- Initialization


	set_callback (a_callback: PROCEDURE [TUPLE [x: REAL_64; y: REAL_64; tx: POINTER; ty: POINTER; a_data: POINTER]])
		do
			set_pltransform_callback_entry (Current, $a_callback)
		end

	on_callback (x: REAL_64; y: REAL_64; tx: POINTER; ty: POINTER; a_data: POINTER)
		local
			l_tx: REAL_64
			l_ty: REAL_64
		do
			l_tx := tr[1] * x + tr[2] * y + tr[3]
			l_ty := tr[4] * x + tr[5] * y + tr[6]
			tx.memory_copy ($l_tx, {PLATFORM}.real_64_bytes)
			ty.memory_copy ($l_tY, {PLATFORM}.real_64_bytes)
		end

	tr: ARRAY [REAL_64]
		do
			Result := << XSPA, 0.0, -1.0, 0.0, YSPA, -1.0 >>
		end


feature -- Access

	XPTS: INTEGER = 35
		-- Data points in x.

	YPTS: INTEGER = 46
		-- Data points in y.

	XSPA: REAL_64
		do
			Result := 2.0 / ( XPTS - 1 )
		end

	YSPA: REAL_64
		do
			Result := 2.0 / ( YPTS - 1 )
		end


feature {ANY}

	plcont (f: PLPLOT_GRID2; nx: INTEGER; ny: INTEGER; kx: INTEGER; lx: INTEGER; ky: INTEGER; ly: INTEGER; clevel: ARRAY [REAL_64]; nlevel: INTEGER; pltr_data: POINTER)
		do
			{PLPLOT_FUNCTIONS_API}.c_plcont (f.pointer, nx, ny, kx, lx, ky, ly, clevel.area.base_address, nlevel, c_dispatcher, pltr_data)
		end

end
